### PR TITLE
CI: enable py312

### PR DESCRIPTION
**Pull request by goneri**

### CODE REVIEW

**Comment by goneri** [comment]
The CI fix is here https://github.com/virt-lightning/virt-lightning/pull/292

**Comment by BubaVV** [comment]
Issue caused by too old flake8. It added support of 3.12 at 6.1.0. I can fix it in separate PR, or just here as follow-up

**Comment by goneri** [comment]
> Issue caused by too old flake8. It added support of 3.12 at 6.1.0. I can fix it in separate PR, or just here as follow-up

Oh great! Yes, please. Open a new PR.

**Comment by BubaVV** [comment]
https://github.com/virt-lightning/virt-lightning/pull/294  However, flake8-logging-format triggers many times

**Comment by goneri** [comment]
@BubaVV Geeeen (finally!) :-)

**Review by BubaVV — APPROVED** [review]
LGTM, everything is green for now

**Pull request merged**
