### PR TITLE
Implemented Github Actions

### PR DESCRIPTION
**Pull request by BubaVV**
mypy is skipped because it mostly for human. For now, black and pep8 reports several low priority issues

### CODE REVIEW

**Comment by goneri** [comment]
Whoa, great :-). I believe you can also drop the `.travis.yml` file. Should we also remove the current `azure-pipelines.yml` file?

**Comment by BubaVV** [comment]
Ok, i also separate linters to separate job for better results presentation. Travis is definitely not needed here, but let's compare results of GA and Azure for several next runs and delete it if we have no regression

**Comment by BubaVV** [comment]
Updated a bit

**Comment by BubaVV** [comment]
> This looks good to me, can you run Black to reindent the files? This way we will be able to merge with a Green CI.

Updated)

**Comment by goneri** [comment]
Sorry, I was away from my computer during the last days. Thank you for the PR. This is really nice :-).

**Pull request merged**
