### PR TITLE
Rename DEBUGING.md to DEBUGGING.md (spelling fix)

### PR DESCRIPTION
**Pull request by musicinmybrain**

### CODE REVIEW

**Comment by musicinmybrain** [comment]
Well, I’m not going to play with GPG for the sake of a trivial drive-by contribution, but someone who can sign the commit may feel free to re-implement this trivial PR.

**Comment by goneri** [comment]
> Well, I’m not going to play with GPG for the sake of a trivial drive-by contribution, but someone who can sign the commit may feel free to re-implement this trivial PR.

Oh, thanks for the feedback. I didn't realize this way such a constraint for the contributors. I disable the option right away.

**Comment by goneri** [comment]
Thank you for the patch :-).

**Comment by musicinmybrain** [comment]
Thanks for following up!

**Pull request merged**
