### PR TITLE
prepare 2.3.2 release

### PR DESCRIPTION
**Pull request by goneri**

### CODE REVIEW

**Comment by goneri** [comment]
The CI fix is here https://github.com/virt-lightning/virt-lightning/pull/292

**Comment by goneri** [comment]
I guess we can release as it is, I will review the Flake8 problem with Python 3.12 later.

**Comment by BubaVV** [comment]
Release planning is always very obscure for me :)

**Comment by goneri** [comment]
Yeah, I know. I realized today that https://github.com/virt-lightning/virt-lightning/commit/e06dece573f312dbce060f7418aa49e29af343ba was not released yet. We should have pushed a release as soon as it was merged.

**Pull request merged**
