### PR TITLE
Change default "meta_data_media_type" to "cdrom"

### PR DESCRIPTION
**Pull request by BubaVV**
Current setup blocks snapshot creation for running instance

Closes: #272

### CODE REVIEW

**Comment by goneri** [comment]
Hi @BubaVV, can you please elaborate a bit regarding the problem?

**Comment by BubaVV** [comment]
Filed an issue with reproduce

**Comment by goneri** [comment]
Great, thank you!

**Comment by goneri** [comment]
@BubaVV Could you add a new block in the README explaining how you use the snapshots? I'm sure this will really interest a lot of users.

**Comment by BubaVV** [comment]
Submitted a PR updating README https://github.com/virt-lightning/virt-lightning/pull/273

**Pull request merged**
