### PR TITLE
make sure shell.up() is allowed to be called twice programmatically

### PR DESCRIPTION
**Pull request by mksh**
When using `virt_lightning` programmatically, I've encountered that `shell.up()` can not be called twice from the same program; attempting to do so produces traceback similar to 

```
  File "...venv/lib64/python3.7/site-packages/virt_lightning/shell.py", line 92, in up
    libvirtaio.virEventRegisterAsyncIOImpl(loop=loop)
  File "...venv/lib64/python3.7/site-packages/libvirtaio.py", line 456, in virEventRegisterAsyncIOImpl
    _current_impl = virEventAsyncIOImpl(loop=loop).register()
  File "...venv/lib64/python3.7/site-packages/libvirtaio.py", line 302, in register
    self._add_timeout, self._update_timeout, self._remove_timeout)
  File "...venv/lib64/python3.7/site-packages/libvirt.py", line 346, in virEventRegisterImpl
    libvirtmod.virEventRegisterImpl(addHandle, updateHandle, removeHandle, addTimeout, updateTimeout, removeTimeout)
RuntimeError: Event loop is already registered
```

This patch makes it possible to call `shell.up` twice from the same asyncio program,
by checking if event loop implementation was registered previously with libvirt against
dictionary of loop instances.

### CODE REVIEW

**Comment by goneri** [comment]
Oh, interesting. Do you consume the `virt_lightning.shell` directly? This module has not been designed to expose a stable API, but it's definitely something that can be improved.
Thanks for the patch, it looks good to me. @zloidemon how do you feel about it?

**Comment by mksh** [comment]
Thanks for the review, @goneri  !

As for usage -- yes, I do consume `virt_lighting.shell` directly.

I am writing a small pet-project now, to allow playing with different versions of stripped down k8s (k3s, minik8s, and similar) on a Linux laptop using qemu/kvm. The codebase consists of 2 parts: VM control part, which spins up requested number of master and agent VMs, and ansible part, which applies various playbooks to VMs to set up k8s. It will be open-sourced on GitHub after well tested :) 

I have found `virt-lightning` a nitpick for such a project, since `virt-lightning` provides API both to spin up // tear down VMs, and Ansible inventory generator :) I have noticed the `shell` API is a flux, but due to nature of my project it will be not a problem to pin version, and also the VM control part I am doing is pluggable, so may be extended to use other tools (esxi, virtualbox-based, etc.) to spin up VMs, or rewritten to use `libvirt` directly in case if `virt_lightning` internal API is restricted past my usage in future.

Unfortunately with every other integration except `virt_lightning` it will be needed to reinvent `shell.ansible_playbook()`, so thank you one more time for good design.

**Comment by goneri** [comment]
Thanks @mksh! It would be nice to prepare a stable API. This is something I'm planning to do since the very beginning and it should not be too complicated to do.

**Comment by goneri** [comment]
Thanks @mksh for the contribution.

**Pull request merged**
